version: '2'

services:
  nginx:
    image: nginx:alpine
    container_name: lemp7-nginx
    ports:
      - '8080:80'
      - '4443:443'
    volumes:
      - '/home/www/:/var/www/html:rw'
      - './nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro'
      - './nginx/ssl:/opt:ro'
      - './logs:/var/log/nginx:rw'
    links:
      - php
    networks:
      translator-net:
        ipv4_address: 10.5.0.3
  php:
    build: ./php7/
    container_name: lemp7-php7
    volumes:
      - '/home/www:/var/www/html:rw'
      - './logs:/var/log/nginx:rw'
    working_dir: '/var/www/html'
    links:
      - database
    networks:
      translator-net:
        ipv4_address: 10.5.0.4
  database:
    image: mysql:5.6
    container_name: lemp7-mysql
    volumes:
      - './mysql/data:/var/lib/mysql:rw'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      translator-net:
        ipv4_address: 10.5.0.5

networks:
  translator-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
